// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLA8bZqDvCq5hLNInqMlUEk0SzId3qlig',
    appId: '1:280815593520:web:43f022d657eafbff8625f5',
    messagingSenderId: '280815593520',
    projectId: 'enablind-db',
    authDomain: 'enablind-db.firebaseapp.com',
    storageBucket: 'enablind-db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz1uXuvPRKqYP9Gg5RjdX_vUJwh3AH1zI',
    appId: '1:280815593520:android:d385295c995b32808625f5',
    messagingSenderId: '280815593520',
    projectId: 'enablind-db',
    storageBucket: 'enablind-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgTC3vzAQgtdgWi29j_z3v8KKsRmy8Xjw',
    appId: '1:280815593520:ios:cf1770e7d8d520538625f5',
    messagingSenderId: '280815593520',
    projectId: 'enablind-db',
    storageBucket: 'enablind-db.appspot.com',
    iosClientId: '280815593520-ei33dthfvduq5du96vuetm2u3qks70q0.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgTC3vzAQgtdgWi29j_z3v8KKsRmy8Xjw',
    appId: '1:280815593520:ios:5373c090a834642e8625f5',
    messagingSenderId: '280815593520',
    projectId: 'enablind-db',
    storageBucket: 'enablind-db.appspot.com',
    iosClientId: '280815593520-6cqp8r11pkbdv7js2dcb7bkcdin19kqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginApp.RunnerTests',
  );
}
